Add adaptive mask plot to report
ME-ICA/tedana pull request #1073
Opened 2024-04-10 20:15 UTC by tsalo

Closes #1072.

Changes proposed in this pull request:

-
-

2024-04-11 18:22 UTC, eurunuela requested changes
Changes look good to me. The only thing I would change is I would make the figure bigger with some css like `style='height: 500px'` or something like that.

2024-04-11 18:47 UTC, eurunuela commented
I think that's better. I noticed the figure has some blank area above and below the actual figure itself. This means that effectively, the brains are not going to be 500px in height, but the whole thing with the blank area above and below will be. I don't know where this blank area came from. It must be from the function that generates the image.

2024-04-11 19:19 UTC, tsalo commented
I dropped the `brainplot` class and things look better. @eurunuela WDYT?

2024-04-12 13:06 UTC, tsalo commented
I'm working on improving the figure- the 3-echo one was looking weird.

2024-04-12 14:56 UTC, tsalo commented
Okay it's looking a lot better now.

<img width="600" alt="Screenshot 2024-04-12 at 10 55 37 AM" src="https://github.com/ME-ICA/tedana/assets/8228902/9e5aebac-4dfd-480d-9e62-7802fc9c189c">

2024-04-12 19:51 UTC, handwerkerd requested changes
The code all looks fine. This will be a useful addition.

Just add explanatory documentation and a picture to the docs. The meaning of the three contours for `base` `optimal combination` and `classification` might not be obvious so explain a bit what they mean.
https://github.com/tsalo/tedana/blob/ab3cbdfbdcd4bac3e4dd42788500c8ad50e0e5a3/docs/outputs.rst#L309

2024-04-12 20:11 UTC, tsalo commented
@handwerkerd WDYT? https://tedana--1073.org.readthedocs.build/en/1073/outputs.html#adaptive-mask-summary-plot

2024-04-12 21:01 UTC, handwerkerd reviewed
Minor, optional change of wording. Just wanted to clarify what 1 & 3 mean.

2024-04-12 21:01 UTC, handwerkerd commented on docs/outputs.rst
> +  This corresponds to values greather than or equal to 3 in the adaptive mask.
```suggestion
  This corresponds to values greater than or equal to 1 (at least 1 good echo) in the adaptive mask.
- **Classification**: The mask used for the decomposition and component classification steps.
  This corresponds to values greather than or equal to 3 (at least 3 good echoes) in the adaptive mask.
```

2024-04-12 21:37 UTC, handwerkerd approved these changes
LGTM!

2024-04-16 11:08 UTC, eurunuela approved these changes
This is great. Thank you @tsalo!

2024-04-16 12:04 UTC, merged