Added link for tedana NeuroStars tag. [DOC]
ME-ICA/tedana pull request #608
Opened 2020-09-22 21:17 UTC by aykhojandi

Closes #593 .

Changes proposed in this pull request:
Update support.rst file to include tedana tag link. 
_Question:_ Should we also edit Line 7 to say "If you would like ... ``tedana`` tag." instead of "... ``multi-echo`` tag." ?(@jbteves and I were wondering this, given that we now want to point tedana-specific questions to the tedana tag).
-
-

2020-09-22 21:19 UTC, jbteves commented
Hey @aykhojandi, thanks for your contribution! Two quick things:
1. Do you mind putting [DOC] at the start, rather than end, of your PR
2. Do you mind making this a Draft PR? Since we're unsure if it's actually ready for review.

2020-09-22 21:22 UTC, aykhojandi commented
Got it, thanks. Made the necessary changes, let me know if something else
stands out as wrong. Best,
Arman

On Tue, Sep 22, 2020 at 5:19 PM Joshua Teves <notifications@github.com>
wrote:

>
>
> Hey @aykhojandi <https://github.com/aykhojandi>, thanks for your
> contribution! Two quick things:
>
>
>
>
>
>    1. Do you mind putting [DOC] at the start, rather than end, of your PR
>
>    2. Do you mind making this a Draft PR? Since we're unsure if it's
>    actually ready for review.
>
>
>
>
>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ME-ICA/tedana/pull/608#issuecomment-696988191>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJCW7UF33IR2N5FK66EBORTSHEIHTANCNFSM4RWIGLXA>
> .
>
>
>

2020-09-22 21:30 UTC, tsalo commented
> Question: Should we also edit Line 7 to say "If you would like ... tedana tag." instead of "... multi-echo tag." ?(@jbteves and I were wondering this, given that we now want to point tedana-specific questions to the tedana tag).

I would say something along the lines of "Please tag any posts about tedana usage with the `tedana` tag and any general questions about multi-echo fMRI with the `multi-echo` tag." Not that exactly, but basically distinguishing the two tags.

2020-09-22 21:48 UTC, tsalo requested changes
A couple of minor adjustments to link to NeuroStars with each of the tags.

2020-09-22 21:48 UTC, tsalo commented on docs/support.rst
> +If you would like to ask a question about tedana-specific usage or tedana's outputs, please submit a question to `NeuroStars`_ with the ``tedana`` tag.
```suggestion
If you would like to ask a question about tedana-specific usage or tedana's outputs, please submit a question to `NeuroStars`_ with the `tedana tag`_.
```

2020-09-22 21:48 UTC, tsalo commented on docs/support.rst
> +If you would like to ask a general question about multi-echo fMRI, please submit it to `NeuroStars`_ with the ``multi-echo`` tag.
```suggestion
If you would like to ask a general question about multi-echo fMRI, please submit it to `NeuroStars`_ with the `multi-echo tag`_.
```

2020-09-22 21:48 UTC, tsalo commented on docs/support.rst
> +.. _tedana: https://neurostars.org/tags/tedana
```suggestion
.. _tedana tag: https://neurostars.org/tags/tedana
```

2020-09-24 16:41 UTC, tsalo commented
@aykhojandi there's just one more change I'd like to see, but this PR is looking great! Do you want to mark it ready for review?

2020-09-24 17:16 UTC, aykhojandi commented
> > Question: Should we also edit Line 7 to say "If you would like ... tedana tag." instead of "... multi-echo tag." ?(@jbteves and I were wondering this, given that we now want to point tedana-specific questions to the tedana tag).
> 
> I would say something along the lines of "Please tag any posts about tedana usage with the `tedana` tag and any general questions about multi-echo fMRI with the `multi-echo` tag." Not that exactly, but basically distinguishing the two tags.



> @aykhojandi there's just one more change I'd like to see, but this PR is looking great! Do you want to mark it ready for review?

Got it. I believe the last suggestion is now committed. I marked this ready for review. Let me know how else I can be of assistance.

2020-09-24 17:26 UTC, tsalo commented
One related thing that would be really helpful is if you could also update the issue template (`.github/ISSUE_TEMPLATE/issue_template.md`), which asks users to use the "multi-echo" NeuroStars tag for usage-related questions. If you could change that to "tedana" that would be awesome.

2020-09-24 18:15 UTC, tsalo approved these changes
LGTM. Thanks for this!

2020-09-28 15:42 UTC, emdupre approved these changes
This LGTM :+1: Thank you, @aykhojandi !

2020-09-28 15:50 UTC, jbteves commented
Oops, sorry I slipped on this. People without write access need to have their PRs merged for them, right? It's been a while.

2020-09-28 15:52 UTC, emdupre commented
> People without write access need to have their PRs merged for them, right? 

Yes :smile_cat: If you also approve, I'll let you pull the trigger !

2020-09-28 16:00 UTC, merged

2020-10-03 21:10 UTC, tsalo commented
@all-contributors please add @aykhojandi for documentation