[DOC] Add NeuroStars question link
ME-ICA/tedana pull request #651
Opened 2021-01-15 17:14 UTC by tsalo

Closes #647.

Changes proposed in this pull request:

- Add link to NeuroStars to issue template selection page.

2021-01-15 19:51 UTC, jbteves requested changes
Singular vs. plural typo; once that's corrected I'll approve.

2021-01-15 19:51 UTC, jbteves commented on .github/ISSUE_TEMPLATE/config.yml
> +      about: Please ask question about using tedana here.
```suggestion
      about: Please ask questions about using tedana here.
```

2021-01-15 19:53 UTC, tsalo commented on .github/ISSUE_TEMPLATE/config.yml
> +      about: Please ask question about using tedana here.
Thx!

2021-01-15 19:55 UTC, jbteves approved these changes
LGTM, thanks for putting this in @tsalo ! That should make it much easier for new users.

2021-01-16 07:32 UTC, eurunuela approved these changes
LGTM!

2021-01-16 15:13 UTC, merged