Update .zenodo.json
ME-ICA/tedana pull request #682
Opened 2021-02-16 20:08 UTC by javiergcas

This pull request includes my information for the .zenodo.json file to be added as a contributor

2021-02-16 20:11 UTC, tsalo requested changes
Just needs a comma in the entry before you to be valid. 

Also, since our release notes come from the PR titles, do you mind if I change the title to 
`"[MAINT] Add Javier Gonzalez-Castillo to Zenodo file"`?

2021-02-16 20:11 UTC, tsalo commented on .zenodo.json
>      }
```suggestion
    },
```

2021-02-16 23:35 UTC, javiergcas commented
Hi Taylor.

That is fine. What do I need to do? Open a new pull request and add the
comma?

Javier.

On Tue, Feb 16, 2021 at 3:11 PM Taylor Salo <notifications@github.com>
wrote:

> *@tsalo* requested changes on this pull request.
>
> Just needs a comma in the entry before you to be valid.
>
> Also, since our release notes come from the PR titles, do you mind if I
> change the title to
> "[MAINT] Add Javier Gonzalez-Castillo to Zenodo file"?
> ------------------------------
>
> In .zenodo.json
> <https://github.com/ME-ICA/tedana/pull/682#discussion_r577104593>:
>
> > @@ -30,6 +30,11 @@
>
>        "affiliation": "National Institutes of Health",
>
>        "orcid": "0000-0001-7261-4042"
>
>      }
>
>
> ⬇️ Suggested change
>
> -    }
>
> +    },
>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ME-ICA/tedana/pull/682#pullrequestreview-591583814>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABXZXNSGT3HLN3JANILVDPLS7LGPHANCNFSM4XXCDTKA>
> .
>

2021-02-17 14:13 UTC, jbteves commented
@javiergcas I'll walk you through it when you get a chance this week, we can message about it separately.

2021-02-17 14:51 UTC, jbteves approved these changes
LGTM, thanks @javiergcas !

2021-02-17 17:15 UTC, tsalo approved these changes
Looks great. Thanks!

2021-02-17 17:28 UTC, merged