Update multi-echo.rst
ME-ICA/tedana pull request #912
Opened 2022-12-01 15:09 UTC by Kasambx

I added the Nashiro dataset link for Heart rate variability biofeedback training and emotion regulation.

2022-12-02 19:48 UTC, handwerkerd requested changes

2022-12-02 19:48 UTC, handwerkerd commented on docs/multi-echo.rst
> +* Nashiro-Dataset_
```suggestion
* Nashiro-Dataset_ - Heart rate variability biofeedback training and emotion regulation
```

Very minor suggestion. 
Thank you for adding this!

2022-12-05 03:06 UTC, Kasambx reviewed
worked on the commit suggestion.

2022-12-13 14:00 UTC, handwerkerd approved these changes
Thank you for adding this!

2022-12-15 16:11 UTC, tsalo approved these changes
LGTM!

2022-12-15 16:13 UTC, dowdlelt approved these changes
I just used this portion of the FAQ the other day, extraordinarily useful. LGTM

2022-12-15 21:18 UTC, merged

2022-12-15 21:19 UTC, tsalo commented
Thanks @Kasambx!

2022-12-16 01:16 UTC, Kasambx commented
Its been a pleasure looking forward to contribute more to your projects.